(function(){
"use strict";
var baseMake=window.makeWorkout,baseSave=window.saveWorkout,baseHistory=window.renderHistory;
var rest=null,ticker=null,folded={};
var SIM={
legPress:["extension","glute","abductor"],extension:["legPress"],curl:["glute"],abductor:["glute","legPress"],adductor:["legPress"],glute:["legPress","abductor"],
row:["pulldown","pullup","rear"],pulldown:["pullup","row"],pullup:["pulldown","row"],rear:["row","pulldown"],
chest:["pec","shoulder"],pec:["chest"],shoulder:["chest","triceps"],biceps:["row","pulldown"],triceps:["chest","shoulder"],calf:["legPress"]
};
var css='.session-v9-tools{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0 14px}.session-v9-clock{border:1.5px solid var(--ink);background:var(--paper);padding:10px 12px;font-weight:900;text-transform:uppercase}.exercise.v9{border:1.5px solid var(--ink);background:var(--paper);margin:0 0 10px;padding:10px}.exercise.v9.complete{background:#f1eee7}.exercise.v9.collapsed>:not(.cardtools-v9):not(.exrow){display:none}.cardtools-v9{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px}.cardsummary-v9{font-size:10px;line-height:1.25;color:var(--muted);font-weight:800}.cardtools-v9 .btn{padding:7px 9px;font-size:9px}.setactions-v9{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.setactions-v9 .done{background:var(--green)}.exerciseactions-v9{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.exerciseactions-v9 .btn{padding:9px 10px;font-size:10px}.swap-v9{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;margin-top:8px}.swap-v9 select{font-size:12px;padding:9px}.saved-v9{display:inline-block;margin-top:8px;padding:5px 8px;border:1px solid var(--ink);background:var(--green);font-size:10px;font-weight:900;text-transform:uppercase}.rest-v9{position:fixed;left:50%;transform:translateX(-50%);bottom:calc(63px + env(safe-area-inset-bottom));width:min(740px,calc(100% - 16px));z-index:45;background:var(--ink);color:var(--cream);border:1px solid var(--cream);padding:10px 12px;display:none;box-shadow:0 4px 18px rgba(0,0,0,.25)}.rest-v9.show{display:block}.rest-v9-grid{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.rest-v9-time{font-size:27px;font-weight:900}.rest-v9-meta{font-size:9px;text-transform:uppercase;color:#cfc7bf}.rest-v9-buttons{display:flex;gap:5px}.rest-v9-buttons button{border:1px solid var(--cream);background:transparent;color:var(--cream);padding:7px 8px;font-weight:900}@media(max-width:560px){.setactions-v9{grid-template-columns:1fr}.exercise.v9{padding:9px}.cardtools-v9{align-items:flex-start}}';
var st=document.createElement("style");st.textContent=css;document.head.appendChild(st);
function fmt(s){s=Math.max(0,Math.round(s||0));return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function sec(){return current&&current.startTime?Math.max(0,Math.floor((Date.now()-current.startTime)/1000)):0}
function saveDraft(){if(current){current.startTime=current.startTime||Date.now();data.activeWorkout=current}else delete data.activeWorkout;if(rest)data.activeRest=rest;else delete data.activeRest;persist()}
function read(id){var r=Object.assign({},current&&current.results&&current.results[id]||{});document.querySelectorAll('[data-id="'+id+'"]').forEach(function(x){var v=x.value;r[x.dataset.f]=v===""?"":(isNaN(Number(v))?v:Number(v))});return r}
function capture(){if(!current)return;current.results=current.results||{};current.ids.forEach(function(id){if(document.querySelector('[data-id="'+id+'"]'))current.results[id]=read(id)});saveDraft()}
function summary(id){var r=current&&current.results&&current.results[id]||{},last=data.last[id]||{},w=r.weight!==undefined&&r.weight!==""?r.weight:(last.weight!==undefined&&last.weight!==""?last.weight:EX[id].defaultLoad),reps=[r.r1,r.r2].filter(function(v){return v!==undefined&&v!==""}).join("/");if(current.completedIds&&current.completedIds.indexOf(id)>=0)return "SAVED · "+w+" kg"+(reps?" · "+reps+" reps":"")+(r.rpe?" · effort "+r.rpe+"/10":"");return current.sets+" set"+(current.sets>1?"s":"")+" × "+DEFAULT_REPS+" · "+w+" kg"}
function ensureTools(){var x=document.getElementById("sessionV9Tools");if(!x){x=document.createElement("div");x.id="sessionV9Tools";x.className="session-v9-tools";var list=document.getElementById("exerciseList");list.parentNode.insertBefore(x,list)}x.innerHTML='<div id="sessionV9Clock" class="session-v9-clock">Session 00:00</div><button class="btn" type="button" onclick="formFoldAll()">Fold all</button><button class="btn" type="button" onclick="formOpenAll()">Open all</button>'}
function tick(){var el=document.getElementById("sessionV9Clock");if(el&&current)el.textContent="Session "+fmt(sec());drawRest()}
function startTicker(){if(ticker)clearInterval(ticker);tick();ticker=setInterval(tick,1000)}
function ensureRest(){var b=document.getElementById("restV9");if(!b){b=document.createElement("div");b.id="restV9";b.className="rest-v9";b.innerHTML='<div class="rest-v9-grid"><div><div id="restV9Time" class="rest-v9-time">01:30</div><div id="restV9Meta" class="rest-v9-meta">Rest between sets</div></div><div class="rest-v9-buttons"><button onclick="formRest(-15)">−15</button><button onclick="formRest(15)">+15</button><button onclick="formRestSkip()">Skip</button></div></div>';document.body.appendChild(b)}return b}
function drawRest(){var b=ensureRest();if(!rest){b.classList.remove("show");return}b.classList.add("show");var rem=Math.max(0,Math.ceil((rest.end-Date.now())/1000)),t=document.getElementById("restV9Time"),m=document.getElementById("restV9Meta");if(rem<=0){if(!rest.done){rest.done=true;saveDraft();try{if(navigator.vibrate)navigator.vibrate([150,80,150])}catch(e){}}t.textContent="REST DONE";m.textContent=(EX[rest.id]?EX[rest.id].name:"Exercise")+" · next set"}else{t.textContent=fmt(rem);m.textContent=(EX[rest.id]?EX[rest.id].name:"Exercise")+" · after set "+rest.set}}
function startRest(id,n){rest={id:id,set:n,end:Date.now()+90000,done:false};saveDraft();drawRest()}
window.formRest=function(d){if(!rest)return;rest.end+=d*1000;rest.done=false;saveDraft();drawRest()};
window.formRestSkip=function(){rest=null;saveDraft();drawRest()};
function options(id){var pref=SIM[id]||[],all=Object.keys(EX).filter(function(k){return k!==id}),ord=pref.concat(all.filter(function(k){return pref.indexOf(k)<0}));return '<option value="">Choose replacement…</option>'+ord.map(function(k){return '<option value="'+k+'">'+(pref.indexOf(k)>=0?"★ similar — ":"")+EX[k].name+'</option>'}).join("")}
function clearExtras(){document.querySelectorAll(".cardtools-v9,.setactions-v9,.exerciseactions-v9,.swap-v9,.saved-v9").forEach(function(x){x.remove()})}
function renumber(){document.querySelectorAll("#exerciseList .exercise").forEach(function(card,i){var n=card.querySelector(".exname");if(n){var txt=n.textContent.replace(/^\d+\s*·\s*/,"");n.textContent=String(i+1).padStart(2,"0")+" · "+txt}})}
function enhance(){if(!current)return;current.startTime=current.startTime||Date.now();current.completedIds=current.completedIds||[];current.setDone=current.setDone||{};current.results=current.results||{};ensureTools();clearExtras();var cards=document.querySelectorAll("#exerciseList .exercise");cards.forEach(function(card,i){var inp=card.querySelector("[data-id]");if(!inp)return;var id=inp.dataset.id;card.classList.add("v9");card.dataset.cardId=id;card.classList.toggle("complete",current.completedIds.indexOf(id)>=0);card.classList.toggle("collapsed",!!folded[id]||current.completedIds.indexOf(id)>=0);var top=document.createElement("div");top.className="cardtools-v9";top.innerHTML='<div class="cardsummary-v9" data-sum="'+id+'">'+summary(id)+'</div><button class="btn" type="button" onclick="formFold(\''+id+'\')">'+(card.classList.contains("collapsed")?"Open":"Fold")+'</button>';card.insertBefore(top,card.firstChild);var fields=card.querySelector(".fields");if(fields){var sets=document.createElement("div");sets.className="setactions-v9";var d=current.setDone[id]||[];sets.innerHTML='<button class="btn '+(d.indexOf(1)>=0?"done":"")+'" type="button" onclick="formSetDone(\''+id+'\',1)">✓ Set 1 done'+(current.sets>1?" + start 90s rest":"")+'</button>'+(current.sets>1?'<button class="btn '+(d.indexOf(2)>=0?"done":"")+'" type="button" onclick="formSetDone(\''+id+'\',2)">✓ Set 2 done</button>':"");fields.insertAdjacentElement("afterend",sets);var act=document.createElement("div");act.className="exerciseactions-v9";act.innerHTML='<button class="btn dark" type="button" onclick="formSaveOne(\''+id+'\')">Save exercise</button><button class="btn" type="button" onclick="formMove(\''+id+'\',-1)">↑ Earlier</button><button class="btn" type="button" onclick="formMove(\''+id+'\',1)">↓ Later</button><button class="btn" type="button" onclick="formLater(\''+id+'\')">Do later</button>';sets.insertAdjacentElement("afterend",act);var sw=document.createElement("div");sw.className="swap-v9";sw.innerHTML='<select id="swapV9-'+id+'">'+options(id)+'</select><button class="btn" type="button" onclick="formSwap(\''+id+'\')">Replace</button>';act.insertAdjacentElement("afterend",sw);if(current.completedIds.indexOf(id)>=0){var ok=document.createElement("span");ok.className="saved-v9";ok.textContent="Exercise saved";sw.insertAdjacentElement("afterend",ok)}}});
renumber();document.querySelectorAll("#exerciseList input").forEach(function(x){x.addEventListener("input",function(){current.results[x.dataset.id]=read(x.dataset.id);saveDraft();var s=document.querySelector('[data-sum="'+x.dataset.id+'"]');if(s)s.textContent=summary(x.dataset.id)})});startTicker();saveDraft()}
window.formFold=function(id){var c=document.querySelector('[data-card-id="'+id+'"]');if(!c)return;var v=c.classList.toggle("collapsed");folded[id]=v;var b=c.querySelector(".cardtools-v9 .btn");if(b)b.textContent=v?"Open":"Fold"};
window.formFoldAll=function(){if(!current)return;current.ids.forEach(function(id){folded[id]=true});enhance()};
window.formOpenAll=function(){folded={};enhance()};
window.formSetDone=function(id,n){if(!current)return;current.results[id]=read(id);var a=current.setDone[id]||[];if(a.indexOf(n)<0)a.push(n);current.setDone[id]=a;saveDraft();enhance();if(n<current.sets)startRest(id,n)};
window.formSaveOne=function(id){if(!current)return;var r=read(id);r.savedAt=new Date().toISOString();current.results[id]=r;if(current.completedIds.indexOf(id)<0)current.completedIds.push(id);data.last[id]=Object.assign({},r);folded[id]=true;saveDraft();enhance();var p=current.ids.indexOf(id),next=null;for(var i=p+1;i<current.ids.length;i++)if(current.completedIds.indexOf(current.ids[i])<0){next=current.ids[i];break}if(next){folded[next]=false;enhance();var c=document.querySelector('[data-card-id="'+next+'"]');if(c)c.scrollIntoView({behavior:"smooth",block:"start"})}};
window.formMove=function(id,d){capture();var i=current.ids.indexOf(id),j=i+d;if(i<0||j<0||j>=current.ids.length)return;var a=current.ids[i];current.ids[i]=current.ids[j];current.ids[j]=a;var c=document.querySelector('[data-card-id="'+id+'"]'),o=document.querySelectorAll("#exerciseList .exercise")[j];if(d<0)o.parentNode.insertBefore(c,o);else o.parentNode.insertBefore(o,c);saveDraft();enhance()};
window.formLater=function(id){capture();var i=current.ids.indexOf(id);if(i<0||i===current.ids.length-1)return;current.ids.splice(i,1);current.ids.push(id);var c=document.querySelector('[data-card-id="'+id+'"]');c.parentNode.appendChild(c);folded[id]=true;saveDraft();enhance()};
function fillCard(card,id){var ex=EX[id],last=data.last[id]||{},w=last.weight!==undefined&&last.weight!==""?last.weight:ex.defaultLoad;card.dataset.cardId=id;card.querySelector(".machine-mini").src=ex.machineImg;card.querySelector(".machine-mini").alt=ex.name+" machine";var n=card.querySelector(".exname");if(n)n.textContent=ex.name;var m=card.querySelector(".exmuscle");if(m)m.textContent=ex.muscles;var cue=card.querySelector(".cue");if(cue)cue.innerHTML="<b>How to do it</b>"+ex.setup+"<br><br><b>Watch out</b>"+ex.watch;var a=card.querySelector(".btnrow a");if(a)a.href=ex.exerciseVideo;var g=card.querySelector(".guideImg");if(g){g.src=ex.guideImg;g.alt=ex.name+" form guide";g.style.display="block"}card.querySelectorAll("[data-id]").forEach(function(x){x.dataset.id=id;if(x.dataset.f==="weight")x.value=w;if(x.dataset.f==="r1")x.value=DEFAULT_REPS;if(x.dataset.f==="r2")x.value=current.sets>1?DEFAULT_REPS:"";if(x.dataset.f==="rpe")x.value=""});var l=card.querySelector(".last");if(l)l.remove()}
window.formSwap=function(id){if(current.completedIds.indexOf(id)>=0){alert("This exercise is already saved.");return}capture();var s=document.getElementById("swapV9-"+id);if(!s||!s.value)return;var nid=s.value;if(current.ids.indexOf(nid)>=0){alert("That machine is already in today's workout.");return}var old=current.results[id],has=old&&Object.keys(old).some(function(k){return old[k]!==""&&old[k]!==undefined});if(has&&!confirm("Replace this exercise? Unsaved numbers entered for it will be removed."))return;var i=current.ids.indexOf(id),card=document.querySelector('[data-card-id="'+id+'"]');current.ids[i]=nid;delete current.results[id];delete current.setDone[id];current.substitutions=current.substitutions||[];current.substitutions.push({from:id,to:nid,at:new Date().toISOString()});delete folded[id];fillCard(card,nid);saveDraft();enhance()};
window.makeWorkout=function(){baseMake();if(!current)return;current.startTime=Date.now();current.completedIds=[];current.setDone={};current.substitutions=[];rest=null;saveDraft();enhance()};
window.saveWorkout=function(){if(!current)return;capture();current.durationSec=sec();current.finishedAt=new Date().toISOString();baseSave();delete data.activeWorkout;delete data.activeRest;persist();rest=null;if(ticker){clearInterval(ticker);ticker=null}drawRest()};
window.renderHistory=function(){baseHistory();var cards=document.querySelectorAll("#history .history-card"),arr=data.sessions.slice().reverse();cards.forEach(function(c,i){var s=arr[i],t=c.querySelector(".history-title");if(s&&s.durationSec&&t&&!c.querySelector(".duration-v9")){var d=document.createElement("div");d.className="small duration-v9";d.textContent="TIME · "+Math.round(s.durationSec/60)+" min";t.insertAdjacentElement("afterend",d)}})};
function restore(){if(!data.activeWorkout)return;var saved=data.activeWorkout;document.getElementById("workoutDate").value=new Date(saved.date).toISOString().slice(0,10);document.getElementById("cycleDay").value=saved.cycleDay||"";document.getElementById("cycleLength").value=saved.cycleLength||28;document.getElementById("energy").value=saved.energy||3;document.getElementById("symptoms").value=saved.symptoms||"none";baseMake();current=saved;current.startTime=current.startTime||Date.now();current.completedIds=current.completedIds||[];current.setDone=current.setDone||{};current.results=current.results||{};rest=data.activeRest||null;var cards=document.querySelectorAll("#exerciseList .exercise");cards.forEach(function(card,i){if(saved.ids[i])fillCard(card,saved.ids[i])});saved.ids.forEach(function(id){var r=saved.results[id];if(r)document.querySelectorAll('[data-id="'+id+'"]').forEach(function(x){if(r[x.dataset.f]!==undefined)x.value=r[x.dataset.f]})});document.getElementById("sessionNotes").value=saved.notes||"";saved.completedIds.forEach(function(id){folded[id]=true});enhance();drawRest()}
ensureRest();setInterval(drawRest,1000);restore();
})();