(function(){
"use strict";
var F=window.FORMV9={rest:null,ticker:null,folded:{}};
F.sim={legPress:["extension","glute","abductor"],extension:["legPress"],curl:["glute"],abductor:["glute","legPress"],adductor:["legPress"],glute:["legPress","abductor"],row:["pulldown","pullup","rear"],pulldown:["pullup","row"],pullup:["pulldown","row"],rear:["row","pulldown"],chest:["pec","shoulder"],pec:["chest"],shoulder:["chest","triceps"],biceps:["row","pulldown"],triceps:["chest","shoulder"],calf:["legPress"]};
var css='.session-v9-tools{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0 14px}.session-v9-clock{border:1.5px solid var(--ink);background:var(--paper);padding:10px 12px;font-weight:900;text-transform:uppercase}.exercise.v9{border:1.5px solid var(--ink);background:var(--paper);margin:0 0 10px;padding:10px}.exercise.v9.complete{background:#f1eee7}.exercise.v9.collapsed>:not(.cardtools-v9):not(.exrow){display:none}.cardtools-v9{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px}.cardsummary-v9{font-size:10px;line-height:1.25;color:var(--muted);font-weight:800}.cardtools-v9 .btn{padding:7px 9px;font-size:9px}.setactions-v9{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.setactions-v9 .done{background:var(--green)}.exerciseactions-v9{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.exerciseactions-v9 .btn{padding:9px 10px;font-size:10px}.swap-v9{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;margin-top:8px}.swap-v9 select{font-size:12px;padding:9px}.saved-v9{display:inline-block;margin-top:8px;padding:5px 8px;border:1px solid var(--ink);background:var(--green);font-size:10px;font-weight:900;text-transform:uppercase}.rest-v9{position:fixed;left:50%;transform:translateX(-50%);bottom:calc(63px + env(safe-area-inset-bottom));width:min(740px,calc(100% - 16px));z-index:45;background:var(--ink);color:var(--cream);border:1px solid var(--cream);padding:10px 12px;display:none}.rest-v9.show{display:block}.rest-v9-grid{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.rest-v9-time{font-size:27px;font-weight:900}.rest-v9-meta{font-size:9px;text-transform:uppercase;color:#cfc7bf}.rest-v9-buttons{display:flex;gap:5px}.rest-v9-buttons button{border:1px solid var(--cream);background:transparent;color:var(--cream);padding:7px 8px;font-weight:900}@media(max-width:560px){.setactions-v9{grid-template-columns:1fr}.exercise.v9{padding:9px}.cardtools-v9{align-items:flex-start}}';
var s=document.createElement("style");s.textContent=css;document.head.appendChild(s);
F.fmt=function(n){n=Math.max(0,Math.round(n||0));return String(Math.floor(n/60)).padStart(2,"0")+":"+String(n%60).padStart(2,"0")};
F.sec=function(){return current&&current.startTime?Math.max(0,Math.floor((Date.now()-current.startTime)/1000)):0};
F.draft=function(){if(current){current.startTime=current.startTime||Date.now();data.activeWorkout=current}else delete data.activeWorkout;if(F.rest)data.activeRest=F.rest;else delete data.activeRest;persist()};
F.read=function(id){var r=Object.assign({},current&&current.results&&current.results[id]||{});document.querySelectorAll('[data-id="'+id+'"]').forEach(function(x){var v=x.value;r[x.dataset.f]=v===""?"":(isNaN(Number(v))?v:Number(v))});return r};
F.capture=function(){if(!current)return;current.results=current.results||{};current.ids.forEach(function(id){if(document.querySelector('[data-id="'+id+'"]'))current.results[id]=F.read(id)});F.draft()};
F.summary=function(id){var r=current&&current.results&&current.results[id]||{},l=data.last[id]||{},w=r.weight!==undefined&&r.weight!==""?r.weight:(l.weight!==undefined&&l.weight!==""?l.weight:EX[id].defaultLoad),reps=[r.r1,r.r2].filter(function(v){return v!==undefined&&v!==""}).join("/");if(current.completedIds&&current.completedIds.indexOf(id)>=0)return "SAVED · "+w+" kg"+(reps?" · "+reps+" reps":"")+(r.rpe?" · effort "+r.rpe+"/10":"");return current.sets+" set"+(current.sets>1?"s":"")+" × "+DEFAULT_REPS+" · "+w+" kg"};
F.ensureRest=function(){var b=document.getElementById("restV9");if(!b){b=document.createElement("div");b.id="restV9";b.className="rest-v9";b.innerHTML='<div class="rest-v9-grid"><div><div id="restV9Time" class="rest-v9-time">01:30</div><div id="restV9Meta" class="rest-v9-meta">Rest between sets</div></div><div class="rest-v9-buttons"><button onclick="formRest(-15)">−15</button><button onclick="formRest(15)">+15</button><button onclick="formRestSkip()">Skip</button></div></div>';document.body.appendChild(b)}return b};
F.drawRest=function(){var b=F.ensureRest();if(!F.rest){b.classList.remove("show");return}b.classList.add("show");var rem=Math.max(0,Math.ceil((F.rest.end-Date.now())/1000)),t=document.getElementById("restV9Time"),m=document.getElementById("restV9Meta");if(rem<=0){if(!F.rest.done){F.rest.done=true;F.draft()}t.textContent="REST DONE";m.textContent=(EX[F.rest.id]?EX[F.rest.id].name:"Exercise")+" · next set"}else{t.textContent=F.fmt(rem);m.textContent=(EX[F.rest.id]?EX[F.rest.id].name:"Exercise")+" · after set "+F.rest.set}};
window.formRest=function(d){if(!F.rest)return;F.rest.end+=d*1000;F.rest.done=false;F.draft();F.drawRest()};
window.formRestSkip=function(){F.rest=null;F.draft();F.drawRest()};
F.startRest=function(id,n){F.rest={id:id,set:n,end:Date.now()+90000,done:false};F.draft();F.drawRest()};
F.ensureRest();setInterval(F.drawRest,1000);
})();