(function(){
"use strict";
var F=window.FORMV10;
F.options=function(id){var p=F.sim[id]||[],a=Object.keys(EX).filter(function(k){return k!==id}),o=p.concat(a.filter(function(k){return p.indexOf(k)<0}));return '<option value="">Choose replacement…</option>'+o.map(function(k){return '<option value="'+k+'">'+(p.indexOf(k)>=0?"★ similar — ":"")+EX[k].name+'</option>'}).join("")};
F.clearExtras=function(){document.querySelectorAll(".cardtools-v10,.setactions-v10,.exerciseactions-v10,.reorder-note-v10,.swap-v10,.saved-v10").forEach(function(x){x.remove()})};
F.renumber=function(){document.querySelectorAll("#exerciseList .exercise").forEach(function(c,i){var n=c.querySelector(".exname");if(n){var t=n.textContent.replace(/^\d+\s*·\s*/,"");n.textContent=String(i+1).padStart(2,"0")+" · "+t}})};
F.ensureTools=function(){var x=document.getElementById("sessionV10Tools");if(!x){x=document.createElement("div");x.id="sessionV10Tools";x.className="session-v10-tools";var list=document.getElementById("exerciseList");list.parentNode.insertBefore(x,list)}
if(!document.getElementById("timerV11Style")){var st=document.createElement("style");st.id="timerV11Style";st.textContent='.timer-media-v11{width:44px;height:44px;padding:0!important;display:grid!important;place-items:center;border:1.5px solid var(--ink)!important;background:var(--paper)!important;color:var(--ink)!important}.timer-media-v11 svg{width:18px;height:18px;display:block;fill:currentColor}.timer-media-v11:active{background:var(--ink)!important;color:var(--cream)!important}.timer-controls-v11{display:flex;gap:6px;align-items:center}';document.head.appendChild(st)}
x.innerHTML='<div id="sessionV10Clock" class="session-v10-clock">Session 00:00</div><div class="timer-controls-v11" aria-label="Session timer controls"><button class="btn timer-media-v11" type="button" onclick="formTimerStart()" aria-label="Start session timer" title="Start"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4l12 8-12 8z"></path></svg></button><button class="btn timer-media-v11" type="button" onclick="formTimerPause()" aria-label="Pause session timer" title="Pause"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 4h4v16H6zM14 4h4v16h-4z"></path></svg></button><button class="btn timer-media-v11" type="button" onclick="formTimerEnd()" aria-label="End session timer" title="End"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 6h12v12H6z"></path></svg></button></div><button class="btn" type="button" onclick="formFoldAll()">Fold all</button><button class="btn" type="button" onclick="formOpenAll()">Open all</button>'};
F.tick=function(){var e=document.getElementById("sessionV10Clock");if(e&&current){var t=F.timerState(),status=t.running?" · RUNNING":(t.ended?" · ENDED":"");e.textContent="Session "+F.fmt(F.elapsed())+status}F.drawRest()};
F.startTicker=function(){if(F.ticker)clearInterval(F.ticker);F.tick();F.ticker=setInterval(F.tick,1000)};
F.enhance=function(){if(!current)return;current.completedIds=current.completedIds||[];current.setDone=current.setDone||{};current.results=current.results||{};F.ensureTools();F.clearExtras();document.querySelectorAll("#exerciseList .exercise").forEach(function(card){var inp=card.querySelector("[data-id]");if(!inp)return;var id=inp.dataset.id;card.classList.add("v10");card.dataset.cardId=id;card.classList.toggle("complete",current.completedIds.indexOf(id)>=0);card.classList.toggle("collapsed",!!F.folded[id]||current.completedIds.indexOf(id)>=0);var top=document.createElement("div");top.className="cardtools-v10";top.innerHTML='<div class="cardsummary-v10" data-sum="'+id+'">'+F.summary(id)+'</div><button class="btn" type="button" onclick="formFold(\''+id+'\')">'+(card.classList.contains("collapsed")?"Open":"Fold")+'</button>';card.insertBefore(top,card.firstChild);var fields=card.querySelector(".fields");if(!fields)return;var done=current.setDone[id]||[],sets=document.createElement("div");sets.className="setactions-v10";sets.innerHTML='<button class="btn '+(done.indexOf(1)>=0?"done":"")+'" type="button" onclick="formSetDone(\''+id+'\',1)">✓ Set 1 done'+(current.sets>1?" + start 90s rest":"")+'</button>'+(current.sets>1?'<button class="btn '+(done.indexOf(2)>=0?"done":"")+'" type="button" onclick="formSetDone(\''+id+'\',2)">✓ Set 2 done</button>':"");fields.insertAdjacentElement("afterend",sets);var act=document.createElement("div");act.className="exerciseactions-v10";act.innerHTML='<button class="btn dark" type="button" onclick="formSaveOne(\''+id+'\')">Save exercise</button><button class="btn" type="button" onclick="formMove(\''+id+'\',-1)">↑ Move up</button><button class="btn" type="button" onclick="formMove(\''+id+'\',1)">↓ Move down</button><button class="btn" type="button" onclick="formToEnd(\''+id+'\')">Send to end</button>';sets.insertAdjacentElement("afterend",act);var note=document.createElement("div");note.className="reorder-note-v10";note.textContent="Move down = one position · Send to end = make it the last exercise";act.insertAdjacentElement("afterend",note);var sw=document.createElement("div");sw.className="swap-v10";sw.innerHTML='<select id="swapV10-'+id+'">'+F.options(id)+'</select><button class="btn" type="button" onclick="formSwap(\''+id+'\')">Replace</button>';note.insertAdjacentElement("afterend",sw);if(current.completedIds.indexOf(id)>=0){var ok=document.createElement("span");ok.className="saved-v10";ok.textContent="Exercise saved";sw.insertAdjacentElement("afterend",ok)}});
F.renumber();document.querySelectorAll("#exerciseList input").forEach(function(x){x.addEventListener("input",function(){current.results[x.dataset.id]=F.read(x.dataset.id);F.draft();var s=document.querySelector('[data-sum="'+x.dataset.id+'"]');if(s)s.textContent=F.summary(x.dataset.id)})});F.startTicker();F.draft()};
window.formFold=function(id){var c=document.querySelector('[data-card-id="'+id+'"]');if(!c)return;var v=c.classList.toggle("collapsed");F.folded[id]=v;var b=c.querySelector(".cardtools-v10 .btn");if(b)b.textContent=v?"Open":"Fold"};
window.formFoldAll=function(){if(!current)return;current.ids.forEach(function(id){F.folded[id]=true});F.enhance()};
window.formOpenAll=function(){F.folded={};F.enhance()};
window.formSetDone=function(id,n){if(!current)return;current.results[id]=F.read(id);var a=current.setDone[id]||[];if(a.indexOf(n)<0)a.push(n);current.setDone[id]=a;F.draft();F.enhance();if(n<current.sets)F.startRest(id,n)};
window.formSaveOne=function(id){if(!current)return;var r=F.read(id);r.savedAt=new Date().toISOString();current.results[id]=r;if(current.completedIds.indexOf(id)<0)current.completedIds.push(id);data.last[id]=Object.assign({},r);F.folded[id]=true;F.draft();F.enhance();var p=current.ids.indexOf(id),next=null;for(var i=p+1;i<current.ids.length;i++)if(current.completedIds.indexOf(current.ids[i])<0){next=current.ids[i];break}if(next){F.folded[next]=false;F.enhance();var c=document.querySelector('[data-card-id="'+next+'"]');if(c)c.scrollIntoView({behavior:"smooth",block:"start"})}};
window.formMove=function(id,d){F.capture();var i=current.ids.indexOf(id),j=i+d;if(i<0||j<0||j>=current.ids.length)return;var tmp=current.ids[i];current.ids[i]=current.ids[j];current.ids[j]=tmp;var c=document.querySelector('[data-card-id="'+id+'"]'),all=document.querySelectorAll("#exerciseList .exercise"),o=all[j];if(d<0)o.parentNode.insertBefore(c,o);else o.parentNode.insertBefore(o,c);F.draft();F.enhance()};
window.formToEnd=function(id){F.capture();var i=current.ids.indexOf(id);if(i<0||i===current.ids.length-1)return;current.ids.splice(i,1);current.ids.push(id);var c=document.querySelector('[data-card-id="'+id+'"]');c.parentNode.appendChild(c);F.folded[id]=true;F.draft();F.enhance()};
F.fillCard=function(card,id){var ex=EX[id],l=data.last[id]||{},w=l.weight!==undefined&&l.weight!==""?l.weight:ex.defaultLoad;card.dataset.cardId=id;var mi=card.querySelector(".machine-mini");if(mi){mi.src=ex.machineImg;mi.alt=ex.name+" machine"}var n=card.querySelector(".exname");if(n)n.textContent=ex.name;var m=card.querySelector(".exmuscle");if(m)m.textContent=ex.muscles;var cue=card.querySelector(".cue");if(cue)cue.innerHTML="<b>How to do it</b>"+ex.setup+"<br><br><b>Watch out</b>"+ex.watch;var a=card.querySelector(".btnrow a");if(a)a.href=ex.exerciseVideo;var g=card.querySelector(".guideImg");if(g){g.src=ex.guideImg;g.alt=ex.name+" form guide";g.style.display="block"}card.querySelectorAll("[data-id]").forEach(function(x){x.dataset.id=id;if(x.dataset.f==="weight")x.value=w;if(x.dataset.f==="r1")x.value=DEFAULT_REPS;if(x.dataset.f==="r2")x.value=current.sets>1?DEFAULT_REPS:"";if(x.dataset.f==="rpe")x.value=""});var last=card.querySelector(".last");if(last)last.remove()};
window.formSwap=function(id){if(current.completedIds.indexOf(id)>=0){alert("This exercise is already saved.");return}F.capture();var s=document.getElementById("swapV10-"+id);if(!s||!s.value)return;var nid=s.value;if(current.ids.indexOf(nid)>=0){alert("That machine is already in today's workout.");return}var old=current.results[id],has=old&&Object.keys(old).some(function(k){return old[k]!==""&&old[k]!==undefined});if(has&&!confirm("Replace this exercise? Unsaved numbers entered for it will be removed."))return;var i=current.ids.indexOf(id),card=document.querySelector('[data-card-id="'+id+'"]');current.ids[i]=nid;delete current.results[id];delete current.setDone[id];current.substitutions=current.substitutions||[];current.substitutions.push({from:id,to:nid,at:new Date().toISOString()});delete F.folded[id];F.fillCard(card,nid);F.draft();F.enhance()};
})();